name: Android build

on:
  workflow_dispatch:
  push:
    branches: ["android"]
  pull_request:
    branches: ["android"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build Cemu for Android
        env:	
          ANDROID_STORE_FILE_BASE64: ${{ secrets.ANDROID_STORE_FILE_BASE64 }}	
          ANDROID_KEY_STORE_PASSWORD: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}	
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}	
        run: |	        
          cd ./src/android	          	
          ./gradlew assembleRelease
          
      - name: build & sign
        if: ${{ github.event.inputs.sign == 'false' }}
        run: |
          cd ${{ env.projectName }}${{ github.event.inputs.repo-dir }}
          chmod +x gradlew
          ./gradlew ${{ github.event.inputs.module }}:assembleRelease -Pandroid.injected.signing.store.file='${{ github.workspace }}/grab-keystore.jks' -Pandroid.injected.signing.store.password='grab-pwd' -Pandroid.injected.signing.key.alias='sign' -Pandroid.injected.signing.key.password='grab-pwd'
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cemu-android
          path: |
            ./src/android/app/build/outputs/apk/release/*.apk
            ./src/android/app/build/outputs/apk/release/*.aab
